### ISSUE TITLE
채팅 기능 구현

### ISSUE THREAD

**Issue by nbmLon99** [pknu-wap/2022_2_WAP_APP_TEAM2#47]
## 📖 작업사항
Firebase를 이용한 채팅 송수신 기능

## To-do

- [x] 채팅 실시간 업데이트 기능
- [x] 메시지 전송 기능
- [x] 알림 기능 (Firebase Cloud Message) 
- [x] FirestoreRecyclerView
- [x] scroll 기능 구현
- [x] 내 메시지와 상대 메시지 layout 분리
