### ISSUE TITLE
영수증 추가/삭제/수정

### ISSUE THREAD

**Issue by pknujsp** [pknu-wap/2022_2_WAP_APP_TEAM2#51]
## 📖 작업사항
영수증 추가/삭제/수정 기능 구현 하기

## To-do
- [x] 파이어베이스 서버에 영수증 데이터 추가
- [x] 파이어베이스 서버내 영수증 데이터 삭제
- [x] 파이어베이스 서버에서 영수증 데이터 수정

## #✔️기타사항
파이어스토어 사용
