### ISSUE TITLE
진행중 정산 화면 최적화

### ISSUE THREAD

**Issue by nbmLon99** [pknu-wap/2022_2_WAP_APP_TEAM2#53]
## 📖 작업사항
 LowerFrame 프래그먼트 분할 

## To-do

- [x] 정산확정 버튼 토글버튼으로 구성
- [x] 프래그먼트 containerview에 연결
- [x] 정산 전 체크박스 프래그먼트 구성
- [x] 정산 후 프래그먼트 구성
- [x] 정산 금액 확정 시 프래그먼트 전환 
- [x] "#,###" 형식으로 금액 표현

## #✔️기타사항
