### ISSUE TITLE
사용자 데이터 받아오는 Repository 구현

### ISSUE THREAD

**Issue by nbmLon99** [pknu-wap/2022_2_WAP_APP_TEAM2#77]
## 📖 작업사항
로그인 시, 사용자 이름 / id / 참여 채팅방 정보를 서버로부터 받아옴 (myAccountViewModel에 변수로 저장)
정산방 참여 시, 참여 사용자정보 받아옴
              (사용자 이름, 사용자 id , token ) map 시킨 후 참여자 정보 modelview에 변수로 저장 

## To-do
- [x] 내 id 받아오기
- [x] 내 참여 채팅방 정보 받아오기
- [x] 그룹 참여 인원 id 받아오기
- [ ] 그룹 참여 인원들의 정보 매핑시켜 저장

## #✔️기타사항
정산방 참여시 매핑된 정보는 서버에서 받아온 메시지 전송자 id의 이름 변환에 사용됨.
