### ISSUE TITLE
달력 연동 기능 구현

### ISSUE THREAD

**Issue by nbmLon99** [pknu-wap/2022_2_WAP_APP_TEAM2#82]
## 📖 작업사항
영수증 등록 시 달력에 표시 -> 색으로 구분

## To-do

- [x] 정산 준비 / 정산 대기 / 정산 확정 영수증별로 달력에 표기
- [x] 다이얼로그 내  클릭시 채팅방 이동
- [x] 색으로 status 구분 필요
- [x] 달력 unscrollabel?? 

## #✔️기타사항
user collection
|- checkReceiptIds              (정산준비)
|-  fixedReceiptIds                (정산대기)
|- completedReceiptIds          (정산확정)
