### ISSUE TITLE
영수증 계산 로직

### ISSUE THREAD

**Issue by EnoughKK** [pknu-wap/2022_2_WAP_APP_TEAM2#88]
## To-do
- [ ]  영수증 레이아웃 수정
- [ ]  파이어베이스 데이터 받기
- [ ]  계산 참여자 데이터 올리기
- [ ]  더치페이 가격 계산 로직

## #✔️기타사항
